<a href="/discount-engine/">&lt;&lt; Back to Discount List</a>

<div id="discount-engine-ng-app" ng-app="discountEngineApp" ng-controller="BaseCtrl" ng-cloak class="ng-cloak">
	<h1>Edit Discount: {{discount.promo_name}}</h1>
	<div class="txt">
		<label>Discount Name:</label>
		<input type="text" ng-model="discount.promo_name"/>
	</div>
	<div class="txt">
		<label>Discount Group</label>
		<select ng-model="discount.dgrp_id" ng-options="group.dgrp_id as group.group_name for group in discount_groups"></select>
	</div>
	<div class="txt">
		<label>Status</label>
		<select ng-model="discount.status" ng-options="status.value as status.label for status in status_options"></select>
	</div>
	<div class="txt">
		<label>Start Date</label>
		 <ng-datetimesimple ng-model="discount.date_available"></ng-datetimesimple>
	</div>
	<div class="txt">
		<label>Expire Date</label>
		<ng-datetimesimple ng-model="discount.expiration"></ng-datetimesimple>
	</div>

	<div class="txt">
		<label>Discount Code(s):</label>
		<span ng-if="!is_global_promo && discount_code_count == 0">
			Discount is <span style="color:red">INCOMPLETE</span> until a choice of code is made.
		</span>	
		<span ng-if="discount_codes.length > 0">
			<span ng-repeat="x in discount_codes">{{x}}{{$last ? '' : ', '}}</span>
			<span ng-if="discount_code_count > 10"> ... ({{discount_code_count}} codes in total)</span>
		</span>
		<span ng-if="is_global_promo">
			GLOBAL PROMO.  All Customers get the discount automatically.
		</span>
		<a class="open-modal" type="iframe" href="/discount-engine/edit-codes/?disc_id=<?= $this->discount->disc_id ?>">(edit)</a>
	</div>

	<div class="clear"></div>
	<div class="txt">
		<label for="main__notes">Notes</label>
		<textarea ng-model="discount.notes" style="width: 300px; height: 75px;"></textarea>
	</div>
	<div class="txt">
		<label for="main__send_email_alerts">Send Email Alerts</label>
		<input type="checkbox" ng-model="discount.send_email_alerts"/><br />
	</div>
	<div class="txt" ng-if="discount.send_email_alerts">
		<label for="main__send_email_alerts_recipients">Send Email Alerts Recipients</label>
		<input maxlength="128" ng-model="discount.send_email_alerts_recipients" />
	</div>

	<div class="clear"></div>
	<h3 style="margin-top: 20px">Discount Attributes:</h3>
	<div ng-repeat="attr in attributes" ng-init="attr_model = attrModel(attr)">
		<div ng-class="['attribute-row',attr.__dependencies_fail ? 'fail' : '']">
			<div class="attr-controls">
				<span class="close" ng-click="removeAttribute(attr.name)">&#10005;</span>
			</div>
			<div class="attr-title">
				{{getAttrInfoByName(attr.name).label}}
			</div>
			<div class="attr-form">
				<ng-include src="'/javascript/discount-engine-app/views/attr/'+ attr.name +'.html'">
			</div>
			<div class="fail-message" ng-if="attr.__dependencies_fail">
				INCOMPATIBLE-ATTRIBUTE.  {{attr.__failed_reason}}
			</div>
		</div>
	</div>
	<div class="attribute-row add-link" ng-if="potential_new_attrs.length > 0">
		<label>Add an Attribute:</label>
		<span class="potential-new-attr" ng-repeat="new_attr in potential_new_attrs" ng-click="addAttribute(new_attr)">
			{{new_attr.label}}
		</span>
		<span class="potential-new-attr" ng-repeat="new_attr in invalid_new_attrs" style="background: lightgray" title="{{new_attr.__failed_reason}}">
			{{new_attr.label}}
		</span>
	</div>
	<div style="text-align: right">
		<input type="submit" onclick="location.href='/discount-engine/'" class="cancel" name="" value="cancel" style="width:auto;" autocomplete="off">
		<input type="submit" ng-click="saveDiscount()" class="submit" name="" value="save discount" style="width:auto;" autocomplete="off">
	</div>
</div>
